name: final_project_amit62
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Customize Flutter's default white native splash screen
  flutter_native_splash: ^2.4.4
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # The Flutter code generator for your assets
  flutter_gen_runner: ^5.7.0
  

  # A build system for Dart code generation
  build_runner: ^2.4.13

  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.9


  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # Customizable animated page indicator
  smooth_page_indicator: ^1.2.0+3


  # State management
  flutter_bloc: ^8.1.3
  # A collection of loading indicators animated with flutter
  flutter_spinkit: ^5.2.1

  # Networking
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # Code generator and handle error  
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1

  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # for dependency injection
  get_it: ^7.6.4


  #Create awesome and powerful modal bottom sheets
  modal_bottom_sheet: ^3.0.0
  # Toast Library for Flutter, Easily create toast messages
  fluttertoast: ^8.2.10
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - lib/core/language/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
